version: "3.8"

networks:
  avail_mainnet_network:
services:
  db:
    image: postgres:15
    networks:
      - avail_mainnet_network
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "3"
    environment:
      POSTGRES_DB: avail_mainnet
      POSTGRES_PASSWORD: postgres
    ports:
      - "${DB_PORT}:5432"
    volumes:
     - /mnt/avail-indexer-mainnet/data/:/var/lib/postgresql/data
    restart: unless-stopped
    
  app:
    build:
      context: .
      dockerfile: Dockerfile
    working_dir: /app
    networks:
      - avail_mainnet_network
    logging:
      driver: "json-file"
      options:
        max-size: "500m"
        max-file: "3"
    volumes:
      - .:/app
    ports:
      - "3001:3000"
    command: ["sqd", "process"]
    env_file:
      - .env
    depends_on: 
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
    restart: unless-stopped

