export * as system from './system/storage'
export * as balances from './balances/storage'
export * as staking from './staking/storage'
export * as nominationPools from './nomination-pools/storage'
export * as identity from './identity/storage'
